---
ansible_user: 'hmueller'
ansible_remote_user: '{{ ansible_user }}'

# used by env_file in containers
http_proxy: ''
https_proxy: ''
no_proxy: '127.0.0.1/8'

# domainname
domainname: '{{ ".".join(ansible_fqdn.split(".")[1:]) }}'

# used by ansible tasks
proxy_env:
  http_proxy: '{{ http_proxy }}'
  https_proxy: '{{ https_proxy }}'
  no_proxy: '{{ no_proxy }}'

elastic_instance_count: '3'

vault_xpack_http_ssl_keystore_password: ''
vault_xpack_transport_ssl_keystore_password: ''
