---
- name: 'Install podman and required packages'
  ansible.builtin.package:
    name:
      - 'podman'
      - 'acl'

- name: 'Setup registry search list'
  ansible.builtin.copy:
    src: 'search.conf'
    dest: '/etc/containers/registries.conf.d/search.conf'
    mode: '0644'

- name: 'Ensure group for podman exists'
  ansible.builtin.group:
    name: '{{ elastic_group }}'
    system: false

- name: 'Ensure user for podman exists with correct gid'
  ansible.builtin.user:
    name: '{{ elastic_user }}'
    group: '{{ elastic_group }}'
    create_home: true
    home: '{{ elastic_home }}'
    password: '!'
    system: false

- name: 'Ensure systemd files directory exists if user not root'
  file:
    path: '{{ elastic_home }}/.config/systemd/user'
    state: 'directory'
    owner: '{{ elastic_user }}'
    group: '{{ elastic_group }}'

- name: 'Enable lingering for podman user'
  ansible.builtin.command:
    cmd: 'loginctl enable-linger {{ elastic_user }}'
    creates: '/var/lib/systemd/linger/{{ elastic_user }}'
