---
- name: Create persistent directories for Elasticsearch
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: '{{ elastic_user }}'
    mode: '0755'
  loop:
    - '{{ elastic_data }}/data'
    - '{{ elastic_data }}/logs'
    - '{{ elastic_data }}/snapshots'
    - '{{ elastic_config }}/certs'
    - '{{ elastic_config }}/config'
