---
- name: 'Include task systemsetup.yml'
  ansible.builtin.include_tasks: 'systemsetup.yml'

# # tasks file for elasticsearch
# - name: Import createdirs
#   ansible.builtin.include_tasks: 'createdirs.yml'

# - name: Include task generatetemplates.yml
#   ansible.builtin.include_tasks: 'generatetemplates.yml'

# - name: Include task synccerts.yml
#   ansible.builtin.include_tasks: 'synccerts.yml'

- name: Include task elastic_stack_podman.yml
  ansible.builtin.include_tasks: 'podman_elasticsearch.yml'
  loop: '{{ range(elastic_host_instances | int) | list }}'
  loop_control:
    loop_var: 'elastic_instance_number'

- name: Create roles and users
  run_once: true
  ansible.builtin.include_tasks: 'create_users.yml'
