---
- name: 'Include task systemsetup.yml'
  ansible.builtin.include_tasks: 'systemsetup.yml'

# - name: Include task synccerts.yml
#   ansible.builtin.include_tasks: 'synccerts.yml'

- name: 'Ensure systemd user directory exists'
  ansible.builtin.file:
    path: '{{ elastic_home }}/.config/systemd/user/default.target.wants'
    state: 'directory'
    owner: '{{ elastic_user }}'
    group: '{{ elastic_group }}'

- name: Include task elastic_stack_podman.yml
  ansible.builtin.include_tasks: 'podman_elasticsearch.yml'
  loop: '{{ range(elastic_host_instances | int) | list }}'
  loop_control:
    loop_var: 'elastic_instance_number'

- name: Create roles and users
  run_once: true
  ansible.builtin.include_tasks: 'create_users.yml'
